### ISSUE TITLE
Export link not working

### ISSUE THREAD

**Issue by meghakundu** [anthonypauwels/ragnarok#8]
The character details can be stored or shared by any means. The conclusion part for the app not proper,after adding the new character with all its preferences you have an option for editing at the samepage,no email verfication and notifying to user about its character.
Thanks about the learning part for UI otherwise. @anthonypauwels If any feature wish to add, kindly add me as contributor would like to work on it.

**Comment by anthonypauwels** [comment]
The rules of the Ragnarok LARP have changed this year, there is no longer a character sheet or skills so this application is no longer necessary. The app will no longer be maintained.

Thank you for your comment.
